# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    build_app(workspace: "Cookd.xcworkspace", scheme: "Cookd")
    pilot(
      ipa: "Cookd.ipa",
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end
end