name: CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000
      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
          bundler-cache: true
      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods
        run: cd ios && arch -x86_64 pod install --repo-update && cd ..
      - name: Upload Build
        env:
            APP_STORE_CONNECT_API_KEY_KEY_ID: PKM7PSG8T7
            APP_STORE_CONNECT_API_KEY_ISSUER_ID: a2188504-3107-4b64-b932-8cb57568b5b5
            APP_STORE_CONNECT_API_KEY_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ25iU24yZmhlbHlJdm9pejkKYjYzTnduRTRCUko3cXNBRWl5d3puczZXL1RTZ0NnWUlLb1pJemowREFRZWhSQU5DQUFTY1E5d1NBdndCd1lhcwo2YnloNlBNTStNaHhVMmJ5MTdKUmIyOVV6OU0rcVZhMmZhQ0RoaUhXcUZNeW9hZmJQUDdaZ0R6VTNrTlpZZCtYCmNMY3lPK0VPCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
            APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: true
            MATCH_PASSWORD: 6283
            MATCH_GIT_BASIC_AUTHORIZATION: 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
        run: bundle exec fastlane release