name: Upload build to App Store

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  upload-build:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_API_KEY_KEY_ID: PKM7PSG8T7
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: a2188504-3107-4b64-b932-8cb57568b5b5
      APP_STORE_CONNECT_API_KEY_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ25iU24yZmhlbHlJdm9pejkKYjYzTnduRTRCUko3cXNBRWl5d3puczZXL1RTZ0NnWUlLb1pJemowREFRZWhSQU5DQUFTY1E5d1NBdndCd1lhcwo2YnloNlBNTStNaHhVMmJ5MTdKUmIyOVV6OU0rcVZhMmZhQ0RoaUhXcUZNeW9hZmJQUDdaZ0R6VTNrTlpZZCtYCmNMY3lPK0VPCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
      APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: true
      MATCH_PASSWORD: 6283
      MATCH_GIT_BASIC_AUTHORIZATION: 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
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload to App Store
        run: fastlane release